GET http://localhost:3000/api/students
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx3eWVyczNAZ21haWwuY29tIiwiaWQiOjEyLCJpYXQiOjE3NDA0MjYzMzksImV4cCI6MTc0MTI5MDMzOX0._7ue1B6e4aElzIqe0GWP7GMKktRN2o2mDkMo38ibMIQ