GET http://localhost:3000/api/students/1/modules
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiaWQiOjEsImlhdCI6MTc0MjY1NzA5MywiZXhwIjoxNzQzNTIxMDkzfQ.0oRNXQ_f5AYO5kb_3C-3mTd1rwJTOE3EiP7BmFc1O_M