GET http://localhost:3000/api/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiaWQiOjEsImlhdCI6MTczNjU4Mzg4NywiZXhwIjoxNzM2NTk4Mjg3fQ.SH2_aXpL68caAgr0oO4EShYOUYA1uoNMQ0c_q5QxY4g