GET http://localhost:3000/api/modules/module-year/74
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiaWQiOjEsImlhdCI6MTczODQwNjEyOCwiZXhwIjoxNzM4NDIwNTI4fQ.9hlguRf_e91aljdIJ7Defi8iENKx-3E3zxS9RhcIhVY