GET http://localhost:3000/api/modules
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiaWQiOjEsImlhdCI6MTczNzgyNTM4MSwiZXhwIjoxNzM3ODM5NzgxfQ.sU0QY-nSod9b8ZjlIdUMkt9n0_YnBQxehxlXAxpj8a4