// SELECT CONCAT('{ forename: "', student.forename,
//   '", surname: "', student.surname,
//   '", student_code: "', student.student_code,
//   '", email: "', student.email,
//   '" },') AS 'student_info'
// FROM student;



const { Student } = require('../../models')

async function seedStudents() {
  const students = await Student.bulkCreate([

    { forename: 'Tom', surname: 'Brown', student_code: 'S00000', email: 'tom.brown@email.com' },
    { forename: 'Mark', surname: 'Eitzel', student_code: 'S00001', email: 'mark.eitzel@email.com' },
    { forename: 'David', surname: 'Thomas', student_code: 'S00002', email: 'david.thomas@email.com' },
    { forename: 'John', surname: 'Martyn', student_code: 'S00003', email: 'john.martyn@email.com' },
    { forename: 'Leonard', surname: 'Cohen', student_code: 'S00004', email: 'leonard.cohen@email.com' },
    { forename: 'Richard', surname: 'Dawson', student_code: 'S00005', email: 'richard.dawson@email.com' },
    { forename: 'Bruno', surname: 'Schultz', student_code: 'S00006', email: 'brun.schultz@email.com' },
    { forename: 'David', surname: 'Tibet', student_code: 'S00007', email: 'david.tibet@email.com' },
    { forename: 'Carissa', surname: 'Weird', student_code: 'S00008', email: 'carissa.weird@email.com' },
    { forename: 'John', surname: 'Thomas', student_code: 'S00009', email: 'john.thomas@email.com' },
    { forename: 'Sam', surname: 'Rice', student_code: 'S00010', email: 'sam.rice@email.com' },
    { forename: 'Alan', surname: 'Anderson', student_code: 'S00011', email: 'alan.anderson@email.com' },
    { forename: 'Betty', surname: 'Anderson', student_code: 'S00012', email: 'betty.anderson@email.com' },
    { forename: 'Claire', surname: 'Anderson', student_code: 'S00013', email: 'claire.anderson@email.com' },
    { forename: 'Declan', surname: 'Anderson', student_code: 'S00014', email: 'declan.anderson@email.com' },
    { forename: 'Emma', surname: 'Anderson', student_code: 'S00015', email: 'emma.anderson@email.com' },
    { forename: 'Frank', surname: 'Anderson', student_code: 'S00016', email: 'frank.anderson@email.com' },
    { forename: 'Gabby', surname: 'Anderson', student_code: 'S00017', email: 'gabby.anderson@email.com' },
    { forename: 'Harry', surname: 'Anderson', student_code: 'S00018', email: 'harry.anderson@email.com' },
    { forename: 'Ignacio', surname: 'Anderson', student_code: 'S00019', email: 'ignacio.anderson@email.com' },
    { forename: 'Jamie', surname: 'Anderson', student_code: 'S00020', email: 'jamie.anderson@email.com' },
    { forename: 'Kelly', surname: 'Anderson', student_code: 'S00021', email: 'kelly.anderson@email.com' },
    { forename: 'Liam', surname: 'Anderson', student_code: 'S00022', email: 'liam.anderson@email.com' },
    { forename: 'Molly', surname: 'Anderson', student_code: 'S00023', email: 'molly.anderson@email.com' },
    { forename: 'Nick', surname: 'Anderson', student_code: 'S00024', email: 'nick.anderson@email.com' },
    { forename: 'Oliver', surname: 'Anderson', student_code: 'S00025', email: 'oliver.anderson@email.com' },
    { forename: 'Peter', surname: 'Anderson', student_code: 'S00026', email: 'peter.anderson@email.com' },
    { forename: 'Quinton', surname: 'Anderson', student_code: 'S00027', email: 'quinton.anderson@email.com' },
    { forename: 'Ryan', surname: 'Anderson', student_code: 'S00028', email: 'ryan.anderson@email.com' },
    { forename: 'Sally', surname: 'Anderson', student_code: 'S00029', email: 'sally.anderson@email.com' },
    { forename: 'Trevor', surname: 'Anderson', student_code: 'S00030', email: 'trevor.anderson@email.com' },
    { forename: 'Ursula', surname: 'Anderson', student_code: 'S00031', email: 'ursula.anderson@email.com' },
    { forename: 'Victor', surname: 'Anderson', student_code: 'S00032', email: 'victor.anderson@email.com' },
    { forename: 'William', surname: 'Anderson', student_code: 'S00033', email: 'william.anderson@email.com' },
    { forename: 'Xander', surname: 'Anderson', student_code: 'S00034', email: 'xander.anderson@email.com' },
    { forename: 'Yasmine', surname: 'Anderson', student_code: 'S00035', email: 'yasmine.anderson@email.com' },
    { forename: 'Zach', surname: 'Anderson', student_code: 'S00036', email: 'zach.anderson@email.com' },
    { forename: 'Alan', surname: 'Benson', student_code: 'S00037', email: 'alan.benson@email.com' },
    { forename: 'Betty', surname: 'Benson', student_code: 'S00038', email: 'betty.benson@email.com' },
    { forename: 'Claire', surname: 'Benson', student_code: 'S00039', email: 'claire.benson@email.com' },
    { forename: 'Declan', surname: 'Benson', student_code: 'S00040', email: 'declan.benson@email.com' },
    { forename: 'Emma', surname: 'Benson', student_code: 'S00041', email: 'emma.benson@email.com' },
    { forename: 'Frank', surname: 'Benson', student_code: 'S00042', email: 'frank.benson@email.com' },
    { forename: 'Gabby', surname: 'Benson', student_code: 'S00043', email: 'gabby.benson@email.com' },
    { forename: 'Harry', surname: 'Benson', student_code: 'S00044', email: 'harry.benson@email.com' },
    { forename: 'Ignacio', surname: 'Benson', student_code: 'S00045', email: 'ignacio.benson@email.com' },
    { forename: 'Jamie', surname: 'Benson', student_code: 'S00046', email: 'jamie.benson@email.com' },
    { forename: 'Kelly', surname: 'Benson', student_code: 'S00047', email: 'kelly.benson@email.com' },
    { forename: 'Liam', surname: 'Benson', student_code: 'S00048', email: 'liam.benson@email.com' },
    { forename: 'Molly', surname: 'Benson', student_code: 'S00049', email: 'molly.benson@email.com' },
    { forename: 'Nick', surname: 'Benson', student_code: 'S00050', email: 'nick.benson@email.com' },
    { forename: 'Oliver', surname: 'Benson', student_code: 'S00051', email: 'oliver.benson@email.com' },
    { forename: 'Peter', surname: 'Benson', student_code: 'S00052', email: 'peter.benson@email.com' },
    { forename: 'Quinton', surname: 'Benson', student_code: 'S00053', email: 'quinton.benson@email.com' },
    { forename: 'Ryan', surname: 'Benson', student_code: 'S00054', email: 'ryan.benson@email.com' },
    { forename: 'Sally', surname: 'Benson', student_code: 'S00055', email: 'sally.benson@email.com' },
    { forename: 'Trevor', surname: 'Benson', student_code: 'S00056', email: 'trevor.benson@email.com' },
    { forename: 'Ursula', surname: 'Benson', student_code: 'S00057', email: 'ursula.benson@email.com' },
    { forename: 'Victor', surname: 'Benson', student_code: 'S00058', email: 'victor.benson@email.com' },
    { forename: 'William', surname: 'Benson', student_code: 'S00059', email: 'william.benson@email.com' },
    { forename: 'Xander', surname: 'Benson', student_code: 'S00060', email: 'xander.benson@email.com' },
    { forename: 'Yasmine', surname: 'Benson', student_code: 'S00061', email: 'yasmine.benson@email.com' },
    { forename: 'Zach', surname: 'Benson', student_code: 'S00062', email: 'zach.benson@email.com' },
    { forename: 'Alan', surname: 'Crilly', student_code: 'S00063', email: 'alan.crilly@email.com' },
    { forename: 'Betty', surname: 'Crilly', student_code: 'S00064', email: 'betty.crilly@email.com' },
    { forename: 'Claire', surname: 'Crilly', student_code: 'S00065', email: 'claire.crilly@email.com' },
    { forename: 'Declan', surname: 'Crilly', student_code: 'S00066', email: 'declan.crilly@email.com' },
    { forename: 'Emma', surname: 'Crilly', student_code: 'S00067', email: 'emma.crilly@email.com' },
    { forename: 'Frank', surname: 'Crilly', student_code: 'S00068', email: 'frank.crilly@email.com' },
    { forename: 'Gabby', surname: 'Crilly', student_code: 'S00069', email: 'gabby.crilly@email.com' },
    { forename: 'Harry', surname: 'Crilly', student_code: 'S00070', email: 'harry.crilly@email.com' },
    { forename: 'Ignacio', surname: 'Crilly', student_code: 'S00071', email: 'ignacio.crilly@email.com' },
    { forename: 'Jamie', surname: 'Crilly', student_code: 'S00072', email: 'jamie.crilly@email.com' },
    { forename: 'Kelly', surname: 'Crilly', student_code: 'S00073', email: 'kelly.crilly@email.com' },
    { forename: 'Liam', surname: 'Crilly', student_code: 'S00074', email: 'liam.crilly@email.com' },
    { forename: 'Molly', surname: 'Crilly', student_code: 'S00075', email: 'molly.crilly@email.com' },
    { forename: 'Nick', surname: 'Crilly', student_code: 'S00076', email: 'nick.crilly@email.com' },
    { forename: 'Oliver', surname: 'Crilly', student_code: 'S00077', email: 'oliver.crilly@email.com' },
    { forename: 'Peter', surname: 'Crilly', student_code: 'S00078', email: 'peter.crilly@email.com' },
    { forename: 'Quinton', surname: 'Crilly', student_code: 'S00079', email: 'quinton.crilly@email.com' },
    { forename: 'Ryan', surname: 'Crilly', student_code: 'S00080', email: 'ryan.crilly@email.com' },
    { forename: 'Sally', surname: 'Crilly', student_code: 'S00081', email: 'sally.crilly@email.com' },
    { forename: 'Trevor', surname: 'Crilly', student_code: 'S00082', email: 'trevor.crilly@email.com' },
    { forename: 'Ursula', surname: 'Crilly', student_code: 'S00083', email: 'ursula.crilly@email.com' },
    { forename: 'Victor', surname: 'Crilly', student_code: 'S00084', email: 'victor.crilly@email.com' },
    { forename: 'William', surname: 'Crilly', student_code: 'S00085', email: 'william.crilly@email.com' },
    { forename: 'Xander', surname: 'Crilly', student_code: 'S00086', email: 'xander.crilly@email.com' },
    { forename: 'Yasmine', surname: 'Crilly', student_code: 'S00087', email: 'yasmine.crilly@email.com' },
    { forename: 'Zach', surname: 'Crilly', student_code: 'S00088', email: 'zach.crilly@email.com' },
    { forename: 'Alan', surname: 'Daniels', student_code: 'S00089', email: 'alan.daniels@email.com' },
    { forename: 'Betty', surname: 'Daniels', student_code: 'S00090', email: 'betty.daniels@email.com' },
    { forename: 'Claire', surname: 'Daniels', student_code: 'S00091', email: 'claire.daniels@email.com' },
    { forename: 'Declan', surname: 'Daniels', student_code: 'S00092', email: 'declan.daniels@email.com' },
    { forename: 'Emma', surname: 'Daniels', student_code: 'S00093', email: 'emma.daniels@email.com' },
    { forename: 'Frank', surname: 'Daniels', student_code: 'S00094', email: 'frank.daniels@email.com' },
    { forename: 'Gabby', surname: 'Daniels', student_code: 'S00095', email: 'gabby.daniels@email.com' },
    { forename: 'Harry', surname: 'Daniels', student_code: 'S00096', email: 'harry.daniels@email.com' },
    { forename: 'Ignacio', surname: 'Daniels', student_code: 'S00097', email: 'ignacio.daniels@email.com' },
    { forename: 'Jamie', surname: 'Daniels', student_code: 'S00098', email: 'jamie.daniels@email.com' },
    { forename: 'Kelly', surname: 'Daniels', student_code: 'S00099', email: 'kelly.daniels@email.com' },
    { forename: 'Liam', surname: 'Daniels', student_code: 'S00100', email: 'liam.daniels@email.com' },
    { forename: 'Molly', surname: 'Daniels', student_code: 'S00101', email: 'molly.daniels@email.com' },
    { forename: 'Nick', surname: 'Daniels', student_code: 'S00102', email: 'nick.daniels@email.com' },
    { forename: 'Oliver', surname: 'Daniels', student_code: 'S00103', email: 'oliver.daniels@email.com' },
    { forename: 'Peter', surname: 'Daniels', student_code: 'S00104', email: 'peter.daniels@email.com' },
    { forename: 'Quinton', surname: 'Daniels', student_code: 'S00105', email: 'quinton.daniels@email.com' },
    { forename: 'Ryan', surname: 'Daniels', student_code: 'S00106', email: 'ryan.daniels@email.com' },
    { forename: 'Sally', surname: 'Daniels', student_code: 'S00107', email: 'sally.daniels@email.com' },
    { forename: 'Trevor', surname: 'Daniels', student_code: 'S00108', email: 'trevor.daniels@email.com' },
    { forename: 'Ursula', surname: 'Daniels', student_code: 'S00109', email: 'ursula.daniels@email.com' },
    { forename: 'Victor', surname: 'Daniels', student_code: 'S00110', email: 'victor.daniels@email.com' },
    { forename: 'William', surname: 'Daniels', student_code: 'S00111', email: 'william.daniels@email.com' },
    { forename: 'Xander', surname: 'Daniels', student_code: 'S00112', email: 'xander.daniels@email.com' },
    { forename: 'Yasmine', surname: 'Daniels', student_code: 'S00113', email: 'yasmine.daniels@email.com' },
    { forename: 'Zach', surname: 'Daniels', student_code: 'S00114', email: 'zach.daniels@email.com' },

  ])
  return students.reduce((acc, student) => ({
    ...acc,
    [`${student.student_code}`]: student.id
  }), {})
}

module.exports = { seedStudents }