const { ModuleYear } = require('../../models')

async function seedModuleYears(modules, semesters, users) {
  const moduleYears = await ModuleYear.bulkCreate([
    { module_id: modules['Introduction to Performing'], year_start: 2021, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Performing'], year_start: 2022, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Performing'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Performing'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Theatre Now: Contemporary Performance'], year_start: 2021, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Theatre Now: Contemporary Performance'], year_start: 2022, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Theatre Now: Contemporary Performance'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Theatre Now: Contemporary Performance'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Production Practices'], year_start: 2021, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Production Practices'], year_start: 2022, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Production Practices'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Production Practices'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Modernist Theatre'], year_start: 2022, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Modernist Theatre'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Modernist Theatre'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Modernist Theatre'], year_start: 2025, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Drama and Mental Health'], year_start: 2022, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Drama and Mental Health'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Drama and Mental Health'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Drama and Mental Health'], year_start: 2025, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Radio Drama'], year_start: 2022, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Radio Drama'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Radio Drama'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Radio Drama'], year_start: 2025, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Adaptation as Interdisciplinary Practice'], year_start: 2022, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Adaptation as Interdisciplinary Practice'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Adaptation as Interdisciplinary Practice'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Adaptation as Interdisciplinary Practice'], year_start: 2025, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Educational Drama'], year_start: 2022, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Educational Drama'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Educational Drama'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Educational Drama'], year_start: 2025, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Advanced Musical Theory'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Advanced Musical Theory'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Advanced Musical Theory'], year_start: 2025, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Advanced Musical Theory'], year_start: 2026, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Advanced Theatre Practice'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Advanced Theatre Practice'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Advanced Theatre Practice'], year_start: 2025, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Advanced Theatre Practice'], year_start: 2026, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Beckett in Performance'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Beckett in Performance'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Beckett in Performance'], year_start: 2025, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Beckett in Performance'], year_start: 2026, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Dance Theatre'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Dance Theatre'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Dance Theatre'], year_start: 2025, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Dance Theatre'], year_start: 2026, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Adaptation as Interdisciplinary Practice'], year_start: 2021, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Adaptation as Interdisciplinary Practice'], year_start: 2022, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Adaptation as Interdisciplinary Practice'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Adaptation as Interdisciplinary Practice'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Editing for Screen'], year_start: 2021, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Editing for Screen'], year_start: 2022, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Editing for Screen'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Editing for Screen'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Film Practice'], year_start: 2021, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Film Practice'], year_start: 2022, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Film Practice'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Film Practice'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Fiction Film Practice'], year_start: 2022, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Fiction Film Practice'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Fiction Film Practice'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Fiction Film Practice'], year_start: 2025, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Popular Genres'], year_start: 2022, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Popular Genres'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Popular Genres'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Popular Genres'], year_start: 2025, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['British Cinema: Nation, Identity and Industry'], year_start: 2022, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['British Cinema: Nation, Identity and Industry'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['British Cinema: Nation, Identity and Industry'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['British Cinema: Nation, Identity and Industry'], year_start: 2025, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Transnational Crime Cinema'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Transnational Crime Cinema'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Transnational Crime Cinema'], year_start: 2025, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Transnational Crime Cinema'], year_start: 2026, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Cinema and the Environment'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Cinema and the Environment'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Cinema and the Environment'], year_start: 2025, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Cinema and the Environment'], year_start: 2026, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Advanced Film Practice 1'], year_start: 2023, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Advanced Film Practice 1'], year_start: 2024, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Advanced Film Practice 1'], year_start: 2025, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Advanced Film Practice 1'], year_start: 2026, semester_id: semesters['Autumn'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Advanced Film Practice 2'], year_start: 2023, semester_id: semesters['Full Year'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Advanced Film Practice 2'], year_start: 2024, semester_id: semesters['Full Year'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Advanced Film Practice 2'], year_start: 2025, semester_id: semesters['Full Year'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Advanced Film Practice 2'], year_start: 2026, semester_id: semesters['Full Year'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Theatre: The Material Stage'], year_start: 2022, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Theatre: The Material Stage'], year_start: 2023, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Theatre: The Material Stage'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Theatre: The Material Stage'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Acting for Stage and Screen'], year_start: 2022, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Acting for Stage and Screen'], year_start: 2023, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Acting for Stage and Screen'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Acting for Stage and Screen'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['The Art of the Actor'], year_start: 2023, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['The Art of the Actor'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['The Art of the Actor'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['The Art of the Actor'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Gender, Culture, and Representation - Backwards & in Heels'], year_start: 2023, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Gender, Culture, and Representation - Backwards & in Heels'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Gender, Culture, and Representation - Backwards & in Heels'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Gender, Culture, and Representation - Backwards & in Heels'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Principles of Business in Arts, Cultural and Creative Industries'], year_start: 2023, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Principles of Business in Arts, Cultural and Creative Industries'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Principles of Business in Arts, Cultural and Creative Industries'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Principles of Business in Arts, Cultural and Creative Industries'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Acting for Musical Theatre'], year_start: 2023, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Acting for Musical Theatre'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Acting for Musical Theatre'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Acting for Musical Theatre'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Acting Shakespeare'], year_start: 2023, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Acting Shakespeare'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Acting Shakespeare'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Acting Shakespeare'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Dramaturgy'], year_start: 2023, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Dramaturgy'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Dramaturgy'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Dramaturgy'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Postconflict Drama: Performing the NI Peace Process'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Postconflict Drama: Performing the NI Peace Process'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Postconflict Drama: Performing the NI Peace Process'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Postconflict Drama: Performing the NI Peace Process'], year_start: 2027, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Solo Performance'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Solo Performance'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Solo Performance'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Solo Performance'], year_start: 2027, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Work-based Learning'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Work-based Learning'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Work-based Learning'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Work-based Learning'], year_start: 2027, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['The Art of Interaction'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['The Art of Interaction'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['The Art of Interaction'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['The Art of Interaction'], year_start: 2027, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Participatory Performance Practices'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Participatory Performance Practices'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Participatory Performance Practices'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Participatory Performance Practices'], year_start: 2027, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Dissertation'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Dissertation'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Dissertation'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Dissertation'], year_start: 2027, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Film Studies 1'], year_start: 2022, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Film Studies 1'], year_start: 2023, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Film Studies 1'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Introduction to Film Studies 1'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Broadcast Journalism'], year_start: 2023, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Broadcast Journalism'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Broadcast Journalism'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Broadcast Journalism'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Experimental Practice'], year_start: 2023, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Experimental Practice'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Experimental Practice'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Experimental Practice'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Creative Enterprise in Film and Digital Media'], year_start: 2023, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Creative Enterprise in Film and Digital Media'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Creative Enterprise in Film and Digital Media'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Creative Enterprise in Film and Digital Media'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Film and Sound: History and Theory'], year_start: 2023, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Film and Sound: History and Theory'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Film and Sound: History and Theory'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Film and Sound: History and Theory'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['World Cinema'], year_start: 2023, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['World Cinema'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['World Cinema'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['World Cinema'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['World Cinema'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['World Cinema'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Documentary Film Studies'], year_start: 2023, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Documentary Film Studies'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Documentary Film Studies'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Documentary Film Studies'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Non-fiction Film Practice'], year_start: 2023, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Non-fiction Film Practice'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Non-fiction Film Practice'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Non-fiction Film Practice'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Media and Time'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Media and Time'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Media and Time'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Media and Time'], year_start: 2027, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Film and Music: Theory and Criticism'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Film and Music: Theory and Criticism'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Film and Music: Theory and Criticism'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Film and Music: Theory and Criticism'], year_start: 2027, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Dissertation'], year_start: 2024, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Dissertation'], year_start: 2025, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Dissertation'], year_start: 2026, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
    { module_id: modules['Dissertation'], year_start: 2027, semester_id: semesters['Spring'], module_coordinator_id: users['john.doe@example.com'] },
  ])
  return moduleYears.reduce((acc, moduleYear) => {
    const moduleName = Object.keys(modules).find(name => modules[name] === moduleYear.module_id)

    if(moduleName) {
      acc[`${moduleName} - ${moduleYear.year_start}`] = moduleYear.id
    }

    return acc
  }, {})
}

module.exports = { seedModuleYears }