GET http://localhost:3000/api/users/1/modules/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiaWQiOjEsImlhdCI6MTc0MDI1MTUyMiwiZXhwIjoxNzQxMTE1NTIyfQ.c6e5gpeLCICjPUBuock7pdFQyryafitQ1bTHHhKdGWQ