name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for backend
        working-directory: ./backend
        run: |
          npm install

      - name: Install dependencies for frontend
        working-directory: ./frontend
        run: |
          npm install

      - name: Run tests for frontend
        working-directory: ./frontend
        run: |
          npm test

      - name: Run tests for backend
        working-directory: ./backend
        run: |
          npm test
