name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for backend
        working-directory: ./backend
        run: |
          npm install

      - name: Install dependencies for frontend
        working-directory: ./frontend
        run: |
          npm install

      # Run ESLint for backend
      - name: Run ESLint for backend
        working-directory: ./backend
        run: |
          npx eslint . --max-warnings=0  # Fail if there are any warnings

      # Run ESLint for frontend
      - name: Run ESLint for frontend
        working-directory: ./frontend
        run: |
          npx eslint . --max-warnings=0  # Fail if there are any warnings

      # Run tests for backend
      - name: Run tests for backend
        working-directory: ./backend
        run: |
          npm test -- --ci --maxWorkers=2  # Adjust maxWorkers if needed

      # Run tests for frontend
      - name: Run tests for frontend
        working-directory: ./frontend
        run: |
          npm test -- --ci --maxWorkers=2  # Adjust maxWorkers if needed


