name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}  # Use GitHub Secrets for sensitive data
          MYSQL_DATABASE: student_marks_test  # You can also put this in secrets if needed
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for backend
        working-directory: ./backend
        run: |
          npm install

      - name: Install dependencies for frontend
        working-directory: ./frontend
        run: |
          npm install

      # Run ESLint for backend
      - name: Run ESLint for backend
        working-directory: ./backend
        run: |
          npx eslint . --max-warnings=0  # Fail if there are any warnings

      # Run ESLint for frontend
      - name: Run ESLint for frontend
        working-directory: ./frontend
        run: |
          npx eslint . --max-warnings=0  # Fail if there are any warnings

      # Set up database connection details for backend tests
      - name: Set up database connection
        run: |
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env  # Fetch username from GitHub Secrets
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env  # Fetch password from GitHub Secrets
          echo "DB_NAME=student_marks_test" >> .env 

      # Add JWT Secret to .env
      - name: Set up JWT secret
        run: |
          echo "JWT_SECRET=${{ secrets.SECRET }}" >> .env  # Fetch JWT secret from GitHub Secrets

      # Run tests for backend
      - name: Run tests for backend
        working-directory: ./backend
        run: |
          npm test -- --ci

      # Run tests for frontend (optional, currently commented out)
      # - name: Run tests for frontend
      #   working-directory: ./frontend
      #   run: |
      #     npm test -- --ci --maxWorkers=2  # Adjust maxWorkers if needed
